/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ambulance.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Ambulance(props) {
  const { nodes, materials } = useGLTF('/ambulance.glb')
  const ref = useRef()
  useFrame(() => {
    ref.current.rotation.y += 0.01
  })
  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, 0.2, 0]}>
        <mesh geometry={nodes.Mesh_body.geometry} material={materials.paintWhite} />
        <mesh geometry={nodes.Mesh_body_1.geometry} material={materials.paintRed} />
        <mesh geometry={nodes.Mesh_body_2.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mesh_body_3.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_body_4.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_body_5.geometry} material={materials.lightFront} />
        <mesh geometry={nodes.Mesh_body_6.geometry} material={materials.window} />
        <mesh geometry={nodes.Mesh_body_7.geometry} material={materials.lightBlue} />
      </group>
      <group position={[-0.55, 0.4, 1.57]}>
        <mesh geometry={nodes.Mesh_doorLeft.geometry} material={materials.paintWhite} />
        <mesh geometry={nodes.Mesh_doorLeft_1.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mesh_doorLeft_2.geometry} material={materials.window} />
        <mesh geometry={nodes.Mesh_doorLeft_3.geometry} material={materials.paintRed} />
      </group>
      <group position={[0.55, 0.4, 1.57]}>
        <mesh geometry={nodes.Mesh_doorRight.geometry} material={materials.paintWhite} />
        <mesh geometry={nodes.Mesh_doorRight_1.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mesh_doorRight_2.geometry} material={materials.window} />
        <mesh geometry={nodes.Mesh_doorRight_3.geometry} material={materials.paintRed} />
      </group>
      <group position={[-0.3, 0.3, 0.91]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group position={[0.3, 0.3, 0.91]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group position={[-0.3, 0.3, -1.01]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group position={[0.3, 0.3, -1.01]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
    </group>
  )
}

useGLTF.preload('/ambulance.glb')
