/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ambulance.gltf
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ambulance(props) {
  const { nodes, materials } = useGLTF('/ambulance.gltf')
  useEffect(() => {
    console.log(nodes)
    console.log(materials)
  }, [])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_body.geometry} material={materials.paintWhite} />
      <mesh geometry={nodes.Mesh_body_1.geometry} material={materials.paintRed} />
      <mesh geometry={nodes.Mesh_body_2.geometry} material={materials.plastic} />
      <mesh geometry={nodes.Mesh_body_3.geometry} material={materials.carTire} />
      <mesh geometry={nodes.Mesh_body_4.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Mesh_body_5.geometry} material={materials.lightFront} />
      <mesh geometry={nodes.Mesh_body_6.geometry} material={materials.window} />
      <mesh geometry={nodes.Mesh_body_7.geometry} material={materials.lightBlue} />
    </group>
  )
}

useGLTF.preload('/ambulance.gltf')
