/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Tree(props) {
  const { nodes, materials } = useGLTF('/tree.gltf')
  const group = useRef()
  useFrame(() => {
    group.current.rotation.y += 0.01
  })
  return (
    <group {...props} dispose={null} ref={group}>
      <group position={[-0.04, -0.02, -0.19]} rotation={[-2.98, -0.49, 1.64]} scale={0.04}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['green.001']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.green} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.brown} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.gltf')
