/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ambulance.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ambulance(props) {
  const { nodes, materials } = useGLTF('/ambulance.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.Mesh_body.geometry} material={materials.paintWhite} />
      <mesh geometry={nodes.Mesh_body_1.geometry} material={materials.paintRed} />
      <mesh geometry={nodes.Mesh_body_2.geometry} material={materials.plastic} />
      <mesh geometry={nodes.Mesh_body_3.geometry} material={materials.carTire} />
      <mesh geometry={nodes.Mesh_body_4.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Mesh_body_5.geometry} material={materials.lightFront} />
      <mesh geometry={nodes.Mesh_body_6.geometry} material={materials.window} />
      <mesh geometry={nodes.Mesh_body_7.geometry} material={materials.lightBlue} />
      <mesh geometry={nodes.Mesh_doorLeft.geometry} material={materials.paintWhite} />
      <mesh geometry={nodes.Mesh_doorLeft_1.geometry} material={materials.plastic} />
      <mesh geometry={nodes.Mesh_doorLeft_2.geometry} material={materials.window} />
      <mesh geometry={nodes.Mesh_doorLeft_3.geometry} material={materials.paintRed} />
      <mesh geometry={nodes.Mesh_doorRight.geometry} material={materials.paintWhite} />
      <mesh geometry={nodes.Mesh_doorRight_1.geometry} material={materials.plastic} />
      <mesh geometry={nodes.Mesh_doorRight_2.geometry} material={materials.window} />
      <mesh geometry={nodes.Mesh_doorRight_3.geometry} material={materials.paintRed} />
    </group>
  )
}

useGLTF.preload('/ambulance.gltf')
